apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: test
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: mylandmarktech/java-web-app
    ports:
    - containerPort: 8080
