apiVersion: v1  
kind: ReplicationController
metadata:
  name: apprc 
spec:
  selector: 
    app: web  
  replicas: 3    
  template:  
    metadata: 
      name: app  
      labels: 
        app: web 
    spec:
      containers:
      - name: app 
        image: mylandmarktech/java-web-app 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: appsvc 
spec: 
  selector: 
    app: web
  type: NodePort
  ports:
  - targetPort: 8080   
    port: 80
    nodePort: 31500
