apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apprs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata:
      name: appps
      labels:
        app: mavenapp
    spec:
      containers:
      - name: apps
        image: legah2045/maven-web-app
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service 
metadata:
  name: app-svc 
spec: 
  selector: 
    app: mavenapp
  type: NodePort
  ports:
  - targetPort: 8080   
    port: 80
    nodePort: 32000 
