apiVersion: v1 
kind: Pod 
metadata: 
  name: webapp
  labels:
    app: webapp
spec:
  imagePullSecrets:
  - name: dhcred  
  containers:
  - name: webapp 
    image: mylandmarktech/nodejs-fe-app:1 
    ports:
    - containerPort: 9981 
---
apiVersion: v1
kind: Service 
metadata:
  name: websvc 
spec: 
  selector: 
    app: webapp
  type: NodePort
  ports:
  - targetPort: 9981   
    port: 80
    nodePort: 31000
